@startuml
!include design.plantuml.txt

actor user as "Healthcare \nProfessional"

box "Healthcare Professional Portal or Primary System" #BFCAD2
	participant app as "App GUI"
  participant docconsumer as "Document Consumer\n(MHD)"
  participant pixmconsumer as "Patient Identifier\nCross-reference\nConsumer"
	participant AuthorizationClient as "Authorization Client\n(IUA)"
end box

box "Community Components" #FFEFDE
	participant mp_pix_x_ref_mgr as "Patient Identifier\nCross-reference\nManger"
	participant mp_AuthorizationServer as "Authorization Server\n(IUA)"
	participant mp_doc_responder as "Document Responder\n(MHD)"
end box

box "IdP" #DFF3F7
	participant idp_user_authentication_provider as "User \nAuthentication \nProvider"
end box

' Sequence starts
user -[#black]> app: read doc
activate app

' Get metadata
app -> mp_AuthorizationServer: GET /.well-known/smart-configuration
activate mp_AuthorizationServer
app <- mp_AuthorizationServer: Conformance statement incl. OAuth 2.1 endpoints
deactivate mp_AuthorizationServer

!include_many step_mh_iua_pixm.plantuml.txt

' Get Access Token (Extended)
!include_many step_mh_iua.plantuml.txt

' Get Document Metadata
app -> docconsumer: query documents\nwith extended access token
activate docconsumer
docconsumer -[#black]> mp_doc_responder: query documents [ITI-67] with extended access token
activate mp_doc_responder
docconsumer <[#black]- mp_doc_responder
deactivate mp_doc_responder
docconsumer <- app
deactivate docconsumer

' Retrieve Document
app -> docconsumer: retrieve documents\nwith extended access token
activate docconsumer
docconsumer -[#black]> mp_doc_responder: retrieve document [ITI-68] with extended access token
activate mp_doc_responder
docconsumer <[#black]- mp_doc_responder
deactivate mp_doc_responder
docconsumer <- app
deactivate docconsumer

user <[#black]- app
deactivate app

@enduml 
