@startuml
!include design.plantuml.txt

actor user as "Healthcare \nProfessional"

box "Healthcare Professional Portal or Primary System" #BFCAD2
  participant app as "App GUI"
  participant docsource as "Document Source\n(MHD)"
  participant pixmconsumer as "Patient Identifier\nCross-reference\nConsumer"
  participant AuthorizationClient as "Authorization Client\n(IUA)"
end box

box "Community Components" #FFEFDE
	participant mp_pix_x_ref_mgr as "Patient Identifier\nCross-reference\nManger"
	participant mp_AuthorizationServer as "Authorization Server\n(IUA)"
	participant mp_doc_recipient as "Document Recipient\n(MHD)"
end box

box "IdP" #DFF3F7
	participant idp_user_authentication_provider as "User \nAuthentication \nProvider"
end box

' Sequence starts
user -[#black]> app: write doc
activate app

' Get metadata
app -> mp_AuthorizationServer: GET /.well-known/smart-configuration
activate mp_AuthorizationServer
app <- mp_AuthorizationServer: Conformance statement incl. OAuth 2.1 endpoints
deactivate mp_AuthorizationServer

' Get Access Token (Basic)
app -[#black]> AuthorizationClient: Get Access Token
activate AuthorizationClient
AuthorizationClient -> mp_AuthorizationServer: [ITI-71] Get Access Token Request \n[Basic access token]
activate mp_AuthorizationServer
mp_AuthorizationServer -> idp_user_authentication_provider: Authenticate User
activate idp_user_authentication_provider
mp_AuthorizationServer <- idp_user_authentication_provider
deactivate idp_user_authentication_provider
mp_AuthorizationServer -[#black]> mp_AuthorizationServer: Authorize App Access
AuthorizationClient <- mp_AuthorizationServer: [ITI-71] Get Access Token Response \n[Basic access token]
deactivate mp_AuthorizationServer
app <[#black]- AuthorizationClient: 
deactivate AuthorizationClient

' Get Patient Identifiers (PIXm)
!include_many step_mh_pixm.plantuml.txt

' Get Access Token (Extended)
!include_many step_mh_iua.plantuml.txt

' Publish Documents
app -> docsource: publish document
!include_many step_mh_mhd_pub.plantuml.txt
docsource <- app
deactivate docsource

user <[#black]- app
deactivate app

@enduml 
