@startuml 

title Interaction Diagram for [ITI-103]

participant "Authorization Client\nor\nResource Server" as Client
participant "Authorization Server" as AuthzServer

autoactivate on
hide footbox

Client -> AuthzServer: Authorization Server Metadata Request
Client <-- AuthzServer: Authorization Server Metadata Response

@enduml