@startuml
hide footbox

title Interaction Diagram for [ITI-91]

participant "Care Services Update\nConsumer" as Client
participant "Care Services Update\nSupplier" as Server

activate Client
activate Server
Client -> Server : Request Care Services Updates Request
Server --> Client : Request Care Services Updates Response
deactivate Server
deactivate Client

@enduml
