@startuml
hide footbox

title Interaction Diagram for [ITI-90]

participant "Query Client" as Client
participant "Directory" as Server

hide footbox
autoactivate on

Client -> Server : Find Matching Care Services Request
Server --> Client : Find Matching Care Services Response

Client -> Server : Retrieve Care Services Resource Request
Server --> Client : Retrieve Care Services Resource Response

@enduml
