@startuml
hide footbox

title Interaction Diagram for [CH:mCSD-1]

participant "Care Services Source" as Client
participant "Care Services Directory" as Server

hide footbox
autoactivate on

== Add ==
Client -> Server : Add Care Service Request
Server --> Client : Add Care Services Response

== Update ==
Client -> Server : Update Care Service Request
Server --> Client : Update Care Services Response

== Delete ==
Client -> Server : Delete Care Service Request
Server --> Client : Delete Care Services Response

@enduml
