@startuml
hide footbox

title Interaction Diagram for [ITI-90]

participant "Care Services Selective\nConsumer" as Client
participant "Care Services Selective\nSupplier" as Server

activate Client
activate Server
Client -> Server : Find Matching Care Services Request
Server --> Client : Find Matching Care Services Response
Client -> Server : Retrieve Care Services Resource Request
Server --> Client : Retrieve Care Services Resource Response
deactivate Server
deactivate Client

@enduml
