@startuml

title Interaction Diagram for [ITI-68]

hide footbox
autoactivate on

participant "Document Consumer" as DocumentConsumer
participant "Document Responder" as DocumentResponder

"DocumentConsumer" -> "DocumentResponder" : Retrieve Document
"DocumentResponder" --> "DocumentConsumer" : Retrieved Document

@enduml 