@startuml

title Interaction Diagram for [ITI-66]

hide footbox
autoactivate on

participant "Document Consumer" as DocumentConsumer
participant "Document Responder" as DocumentResponder

"DocumentConsumer" -> "DocumentResponder" : Find Document Lists Request
"DocumentResponder" --> "DocumentConsumer" : Find Document Lists Response

@enduml 