@startuml

title Interaction Diagram for [ITI-66]

participant "Document Consumer" as DocumentConsumer
participant "Document Responder" as DocumentResponder
activate "DocumentConsumer"
activate "DocumentResponder"
"DocumentConsumer" -> "DocumentResponder" : 1. Find Document Lists [ITI-66]
return
deactivate "DocumentConsumer"
deactivate "DocumentResponder"

@enduml 