@startuml

title Interaction Diagram for [ITI-66]

participant consumer as "Document\nConsumer"
participant responder as "Document\nResponder"

consumer -> responder: Find Document Lists Request Message
activate consumer
activate responder

responder -> consumer: Find Document Lists Response Message
deactivate responder
deactivate consumer

@enduml 