@startuml

title Interaction Diagram for [CH:MHD-1]

hide footbox
autoactivate on

participant "Document Source" as DocumentSource
participant "Document Responder" as DocumentResponder

"DocumentSource" -> "DocumentResponder" : Request to Update Document Metadata
"DocumentResponder" --> "DocumentSource" : Updated DocumentReference Response

@enduml 