@startuml

title Interaction Diagram for [ITI-67]

hide footbox
autoactivate on

participant "Document Consumer" as DocumentConsumer
participant "Document Responder" as DocumentResponder

"DocumentConsumer" -> "DocumentResponder" : Find Document References Request
"DocumentResponder" --> "DocumentConsumer" : Find Document References Response

@enduml 