@startuml

title Interaction Diagram for [CH:MHD-1]

hide footbox
autoactivate on

participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient

"DocumentSource" -> "DocumentRecipient" : Request to Update Limited Document Metadata
"DocumentRecipient" --> "DocumentSource" : Updated DocumentReference Response

@enduml 