@startuml

title Interaction Diagram for [ITI-65]

hide footbox
autoactivate on

participant "Document Source" as DocumentSource
participant "Document Recipient" as DocumentRecipient

"DocumentSource" -> "DocumentRecipient" : Request to publish documents
"DocumentRecipient" --> "DocumentSource" : Documents published

@enduml 