@startuml
skinparam responseMessageBelowArrow true
hide footbox

actor User 
participant "User Agent" as UI
participant "Relying Party" as RP
participant "Verifier (IdP)" as IdP

autonumber 1 1 "<b>[00]"

RP -> UI: Redirect with Logout Request [HTTP]
UI -> IdP: http GET request 

|||

IdP -> UI: Present logout screen
User -> UI: Logout
UI -> IdP: Logout
IdP -> IdP: terminate user session

|||

IdP -> UI: Redirect to post logout url
UI -> RP: Redirect

RP -> RP: terminate user session

autonumber stop

@enduml
