@startuml

title Interaction Diagram for [ITI-83]

hide footbox
autoactivate on

participant consumer as "Patient Identifier Cross-reference Consumer"
participant manager as "Patient Identifier Cross-reference Manager"

consumer -> manager : Get Corresponding Identifiers
manager --> consumer: Response

@enduml 