@host = http://test.ahdis.ch/fhir

GET {{host}}/metadata HTTP/1.1
Accept: application/fhir+json


############ Register Patient Data ############


### ITI-104 Mobile Patient Identity Feed
POST {{host}}/$process-message HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./test/PmirFeed.json
    ### Response: PmirResponse.json   


############ Submit Document (Patient MAG-002) ############


### ITI-83 Mobile Patient Identifier Cross-Reference Query (PIXm)
    ### sourceIdentifier: AssigningAuthority|PatientLocalId
    ### targetSystem: AssigningAuthority (MPI-PID)
GET {{host}}/Patient/$ihe-pix?sourceIdentifier=urn:oid:1.3.6.1.4.1.21367.2017.2.7.109|localpid&targetSystem=urn:oid:1.3.6.1.4.1.21367.2017.2.5.83 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
   ### Response: targetId = Patient/1.3.6.1.4.1.21367.2017.2.5.83-MAG-002


### ITI-65 Request (MHD: Provide Document Bundle)
    ### Patient: subject reference (DocumentReference & List) from PIXm Query=  http://test.ahdis.ch/fhir/Patient/1.3.6.1.4.1.21367.2017.2.5.83-MAG-002
    ### Note for testing: When submitting a bundle, increase the masterIdentifier (DocumentReference & List)
POST {{host}}/ HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

< ./test/MAG-002_BundleProvideDocument.json
    ### Response: MAG-002_Response-ITI-65.json

### ITI-66 Request (MHD: Find Document Manifests -> Deprecated)
### GET {{host}}/DocumentManifest?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.2017.2.5.83|MAG-002 HTTP/1.1
### Accept: application/fhir+json
## Content-Type: application/fhir+json
    ### Response: MAG-002_Response-ITI-66.json

### ITI-66 Request (MHD: Find Document List)
GET {{host}}/List?code=submissionset&status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.2017.2.5.83|MAG-002 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json


### Response: MAG-002_Response-ITI-66.json


### ITI-67 Request (MHD: Find Document References)
GET {{host}}/DocumentReference?status=current&patient.identifier=urn:oid:1.3.6.1.4.1.21367.2017.2.5.83|MAG-002 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
    ### Response: MAG-002_Response-ITI-67.json


### ITI-68 Request (MHD: Retrieve Document -> Medication Card document (CDA))
    ### DocumentReference.content.attachment.url from Find Document Reference
GET http://test.ahdis.ch/camel/xdsretrieve?uniqueId=1.3.6.1.4.1.12559.11.13.2.1.3008&repositoryUniqueId=1.1.4567332.1.2
Accept: application/fhir+json
