id: ch.fhir.ig.ch-epr-mhealth
canonical: http://fhir.ch/ig/ch-epr-mhealth/ImplementationGuide/ch.fhir.ig.ch-epr-mhealth
name: CHEprMhealth
fhirVersion: 4.0.1
status: active
copyrightYear: 2020+
releaseLabel: ci-build
dependencies:
  ch.fhir.ig.ch-epr-term: 2.0.5
  ch.fhir.ig.ch-core: 2.0.0
  IHE.ITI.PIXm: 3.0.0
  ihe.mhd.fhir: 4.0.2